---
title: "Dividing R functions"
author: "Judith Neve"
date: "25/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(CTmeta)
library(ChiBarSq.DiffTest)
library(goric)
```

# Installing the packages

```{r}
functions.to.check <- c(ls("package:CTmeta"), ls("package:ChiBarSq.DiffTest"), "restriktor::goric")
```

# Division of work

```{r}
Judith <- functions.to.check[c(1:13, 28)]
Alex <- functions.to.check[c(14:27)]
Judith
Alex
```

# Done

```{r}
Judith <- Judith[Judith != "CTmeta"]
Judith <- Judith[Judith != "coef.CTmeta"]
# no need to actually look at coef.CTmeta, this just makes coef() work
Judith <- Judith[Judith != "Area"]
Judith <- Judith[Judith != "ChecksCTM"]
Judith <- Judith[Judith != "CTMparam"]
Judith <- Judith[Judith != "DiagDeltaT"]

Judith <- Judith[Judith != "myData"]
Judith <- Judith[Judith != "myDrift"]
Judith <- Judith[Judith != "myGamma"]
# no need to look at these, they are example datasets
Judith
```

eigen(summary(Phi)$DRIFT)$val -- for PhiPlot function, if multiple plots are produced in one plot because Phi does not have a single solution

go back to CTmeta

