---
title: "To-do list for function checking"
author: "Judith Neve"
date: "04/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Workflow

1. Extensively check function

2. Modify function as per checks

3. Read through function: is there anything (especially regarding errors/warnings) that should still be changed?

4. Discussion with Rebecca about unclear parts

5. Go through the function check process again

6. Modify documentation


# For each function:

## CTmeta

### Workflow

1. Extensively check function

Done.

2. Modify function as per checks

Done.

3. Read through function: is there anything (especially regarding errors/warnings) that should still be changed?

Done.

4. Discussion with Rebecca about unclear parts

a. Some of the bigger essence changes are cutting out "currently, ... is of size ..." for matrices: giving a vector of dimensions does not provide clear enough information, and formatting it such that the dimensions are given is more hassle than necessary for an error message that clearly states the size it should be.

5. Go through the function check process again

6. Modify documentation

Done.

### Don't forget:

1. Label

2. PrintPlot: error message when the plot can't be made

The question has been sent to Rebecca.

3. How to deal with both Gamma and SigmaVAR being specified - which one is more important? What if one of them is broken? What if they don't match?

Notes:

* it appears that neither can be broken - otherwise, we get errors.

* if both are specified, it seems Gamma takes precendence

4. How does BetweenLevel work?

### Smaller notes:

1. "The arguments SigmaVAR and Gamma are not found: Both SigmaVAR and Gamma are unknown; either one (or both) should be part of the input. In case of first matrix, specify 'SigmaVAR = SigmaVAR'."

What does this mean?

2. How do we deal with Phi that has too many columns?

Can't include an if statement for the case where it has more columns than q since q is defined from Phi.

3. Warning if vector for "Moderators":

Actually comes up with a bunch of warnings - it is clear what the problem is from them, but should this be reduced to just one?

4. Can moderators be factors?

This would explain the output of the non-numerical moderator input

5. What do the entries in BetweenLevel mean?

i.e.: does it make a difference whether it's 0, 1, 2 or 1, 2, 3?

6. When PhiPlot = TRUE, the plot prints twice

7. What exactly should be in N?